### ISSUE TITLE
Contrast Issue in Header bar with Alternatate icon themes.

### ISSUE THREAD

**Issue by arshubham** [mirkobrombin/PPAExtender#10]
I am using ePapirus 
![screenshot from 2017-11-09 16 22 41](https://user-images.githubusercontent.com/14235191/32601948-5b38450e-c56a-11e7-8ff4-67bbce3693fc.png)

It would be great if you can provide Ability to change or disable headerbar color.

**Comment by mirkobrombin** [comment]
The application is born as elementary "native", although it is not available in the App Center.
Support for different icons is not foreseen, I'll see in the future.

**Comment by arshubham** [comment]
I understand that it will never be in appcenter but at least a non colored (default) header bar is better for compatibility with all the icon packs.

**Comment by mirkobrombin** [comment]
Fixing in next release.
