### ISSUE TITLE
Ability to disable ppa without deleting it.

### ISSUE THREAD

**Issue by arshubham** [mirkobrombin/PPAExtender#11]
Like what is provided in Software and Updates
![screenshot from 2017-11-09 16 29 56](https://user-images.githubusercontent.com/14235191/32602198-3f1361be-c56b-11e7-8184-4be5c7847978.png)

**Comment by mirkobrombin** [comment]
Howto: Using sources.list I can disable the entries by commenting on the lines.

**Comment by mirkobrombin** [comment]
I will add this here:
https://github.com/linuxhubit/ppaextender#todo
