### ISSUE TITLE
Ability to Enable proposed repo

### ISSUE THREAD

**Issue by arshubham** [mirkobrombin/PPAExtender#12]
This should be added as it prevents resorting to Software and updates or editing sources.
![screenshot from 2017-11-09 16 32 33](https://user-images.githubusercontent.com/14235191/32602286-9bfcb3a8-c56b-11e7-8544-3a8945f7a693.png)

**Comment by mirkobrombin** [comment]
I'm adding this feature in the new version of ppaextender.

https://github.com/linuxhubit/ppaextender/commit/b67f0aaaddc741b9b74498ddf0ef6de5703db2a1
