### ISSUE TITLE
Show a message when updating cache

### ISSUE THREAD

**Issue by arshubham** [mirkobrombin/PPAExtender#13]
Show a message when updating cache instead of just a spinner.  A dialog box or a tooltip on the spinner if possible.

**Comment by mirkobrombin** [comment]
I think a spinner is quite intuitive. It might be an idea to block the widgets until the end of the process.

**Comment by arshubham** [comment]
Yeah, spinner is fine but for better U/X  a tooltip can be shows on hovering over the spinner showing what exactly it is doing.  Software and updates currently shows a progress bar which can be expanded to show the cache update percentages for each repo. 

A similar issue is also open in appcenter:  https://github.com/elementary/appcenter/issues/394

**Comment by mirkobrombin** [comment]
I will add this here:
https://github.com/linuxhubit/ppaextender#todo
