### ISSUE TITLE
App rejected

### ISSUE THREAD

**Issue by cassidyjames** [mirkobrombin/PPAExtender#8]
Thank you for submitting your app! However, we've decided not to publish it in AppCenter due to the security and stability implications of modifying software sources. To help avoid a similar situation in the future, we will be modifying our AppCenter publishing guidelines to let developers know that these types of apps will not be published. Thank you for your time, and we hope to see future apps from you published in AppCenter!

**Comment by mirkobrombin** [comment]
Ready to publish new ones!
